### ISSUE TITLE
Invalid syntax on Jekyll build

### ISSUE THREAD

**Issue by devilgate** [allejo/jekyll-toc#12]
I'm not sure if I'm doing something wrong, as I've never used Liquid before, and I'm brand-new to Jekyll; but I get an error when I try to build my site.

**My Markdown**

```markdown
# 1. What is the RIF?

The Rapid Inquiry Facility (RIF) is a freely available software application that supports two types of environmental health activities:

## 1.1 Study Aims

## 1.2 References

# 2. What does the RIF do?

## 2.1. Screen Shots

### 2.1.1 Screenshot of the old RIF 3.x

### 2.1.2 Screenshots of the new RIF 4.0

# 3. Authors

## MRC-PHE Centre for Environment and Health

## UK Small Area Health Statistics Unit (SAHSU)

# 4. Funders

## 4.1 Collaborators

## 4.2 Other Contributors


## 5. Licensing

# 6. Build and Install

## 6.1 Postgres

### 6.1.1 Building the RIF Postgres database

### 6.1.2 Installing the RIF Postgres Database

### 6.1.3 Extra Configuration

## 6.2 Microsoft SQL Server

### 6.2.1 Building the RIF SQL Server Database

### 6.2.2 Installing the RIF SQL Server Database

## 6.3 Web Services

### 6.3.1 Taxonomy Services

## 6.4 Data Loading

### 6.4.1 Manual Data Loading

### 6.4.2 Using the Data Loading Tool

# 7. Manuals

# 8. For Developers

## RIF Architecture

# 9. TODO list

```

**TOC Usage**

I'm just accepting the defaults. 

```twig
{% include toc.html html=content %}
```

**Expected TOC**

Anything at all!

```html

```

**Actual TOC**

No HTML generated. Got the following error output instead:

```
| => jekyll build --trace
Configuration file: /Users/martin/Dropbox/work/sahsu/rapidInquiryFacility/docs/_config.yml
            Source: /Users/martin/Dropbox/work/sahsu/rapidInquiryFacility/docs
       Destination: /Users/martin/Dropbox/work/sahsu/rapidInquiryFacility/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Liquid Exception: Invalid syntax for include tag: html=content sanitize=true class=&quot;inline_toc&quot; id=&quot;my_toc&quot; h_min=2 h_max=3 Valid syntax: {% include file.ext param='value' param2='value' %} in index.md
Traceback (most recent call last):
	54: from /usr/local/bin/jekyll:23:in `<main>'
	53: from /usr/local/bin/jekyll:23:in `load'
	52: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
	51: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	50: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	49: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	48: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	47: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	46: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	45: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
	44: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
	43: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
	42: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:73:in `process'
	41: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:191:in `render'
	40: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:471:in `render_pages'
	39: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:471:in `each'
	38: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:473:in `block in render_pages'
	37: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:62:in `run'
	36: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:76:in `render_document'
	35: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:123:in `render_liquid'
	34: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	33: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/tags/include.rb:132:in `render'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/tags/include.rb:166:in `load_cached_partial'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:116:in `parse'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:132:in `parse'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block.rb:10:in `parse'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block.rb:51:in `parse_body'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block.rb:10:in `parse'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block.rb:51:in `parse_body'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/tag.rb:9:in `parse'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/tag.rb:9:in `new'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/tags/include.rb:33:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/tags/include.rb:79:in `validate_params': Invalid syntax for include tag: (ArgumentError)

  html=content sanitize=true class=&quot;inline_toc&quot; id=&quot;my_toc&quot; h_min=2 h_max=3

Valid syntax:

  {% include file.ext param='value' param2='value' %}

```

**Notes**

As you can see from my Markdown, I'm trying to replace a manually-maintained table of contents with an automatically-generated one, so this tag should be ideal.

**Comment by allejo** [comment]
> `Liquid Exception: Invalid syntax for include tag: html=content sanitize=true class=&quot;inline_toc&quot; id=&quot;my_toc&quot; h_min=2 h_max=3`

This is telling me that somewhere, somehow, the `toc.html` is being converted into HTML before it's being treated as Liquid because the `"`s are being converted into HTML entities.

Do you have a public repository where I'd be able to reproduce this issue?

Otherwise, things to try/keep in mind:

- Download the `toc.html` file as "raw" from GitHub or from a tagged release
- Make sure the `toc.html` file is inside of `_includes` so it's not processed as HTML

**Comment by devilgate** [comment]
Ah, thanks, it was that I hadn't downloaded the raw version.
